import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(String role) {
        initComponents();
        setLocationRelativeTo(null);
        if(role.equals("Admin")) {
            btnUSER.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUSER = new javax.swing.JButton();
        CATEGORY = new javax.swing.JButton();
        btnUniform = new javax.swing.JButton();
        btnOfficer = new javax.swing.JButton();
        DISTRIBUTION = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        ViewDistribution = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUSER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        btnUSER.setText("User");
        btnUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSERActionPerformed(evt);
            }
        });
        getContentPane().add(btnUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        CATEGORY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CATEGORY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        CATEGORY.setText("Category");
        CATEGORY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATEGORYActionPerformed(evt);
            }
        });
        getContentPane().add(CATEGORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        btnUniform.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUniform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uniform .png"))); // NOI18N
        btnUniform.setText("Uniform");
        btnUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniformActionPerformed(evt);
            }
        });
        getContentPane().add(btnUniform, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        btnOfficer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOfficer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/personnel.png"))); // NOI18N
        btnOfficer.setText("OFFICERS");
        btnOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficerActionPerformed(evt);
            }
        });
        getContentPane().add(btnOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        DISTRIBUTION.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DISTRIBUTION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Distribution.png"))); // NOI18N
        DISTRIBUTION.setText("Distribution");
        DISTRIBUTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISTRIBUTIONActionPerformed(evt);
            }
        });
        getContentPane().add(DISTRIBUTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        LOGOUT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        LOGOUT.setText("Logout");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, -1));

        ViewDistribution.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewDistribution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View-Distribution.png"))); // NOI18N
        ViewDistribution.setText("View Distribution ");
        getContentPane().add(ViewDistribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 200, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CATEGORYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATEGORYActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_CATEGORYActionPerformed

    private void btnOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficerActionPerformed
        // TODO add your handling code here:
        new ManageOfficer().setVisible(true);
    }//GEN-LAST:event_btnOfficerActionPerformed

    private void DISTRIBUTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISTRIBUTIONActionPerformed
        // TODO add your handling code here:
        new ManageDistribution().setVisible(true);
    }//GEN-LAST:event_DISTRIBUTIONActionPerformed

    private void btnUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSERActionPerformed
        // TODO add your handling code here:
        new ManageUser().setVisible(true);  
    }//GEN-LAST:event_btnUSERActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout application?", "Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void btnUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniformActionPerformed
        // TODO add your handling code here:
        new ManageUniform().setVisible(true);
    }//GEN-LAST:event_btnUniformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CATEGORY;
    private javax.swing.JButton DISTRIBUTION;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton ViewDistribution;
    private javax.swing.JButton btnOfficer;
    private javax.swing.JButton btnUSER;
    private javax.swing.JButton btnUniform;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
