/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import static common.OpenPdf.OpenById;
import dao.ConnectionProvider;
import dao.DistributionUtils;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author admin
 */
public class ManageDistribution extends javax.swing.JFrame {

    private int officerPk = 0;
    private int uniformPk = 0;
    private int finalTotalPrice = 0;

    private String distributionId = "";

    /**
     * Creates new form ManageDistribution
     */
    public ManageDistribution() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void clearUniformFields() {
        uniformPk = 0;
        txtUniformName.setText("");
        txtUniformDescription.setText("");
        txtDistributionQuantity.setText("");
    }

    public String getUniqueId(String prefix) {
        return prefix + System.nanoTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfficer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUniform = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDistributionList = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOfficerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOfficerRank = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOfficerPhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUniformName = new javax.swing.JTextField();
        txtUniformDescription = new javax.swing.JTextField();
        txtDistributionQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblFinalTotalPrice = new javax.swing.JLabel();
        btnSaveDistributionDetails = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUniformPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setText("Manage Distribution");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Officer List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 95, -1, -1));

        tableOfficer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Rank", "Phone Number"
            }
        ));
        tableOfficer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOfficerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOfficer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 129, 389, 221));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Uniform List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 95, -1, -1));

        tableUniform.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Qty", "Description", "Cat ID", "Cat Name"
            }
        ));
        tableUniform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUniformMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUniform);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 129, -1, 221));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Distribution List");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1089, 95, -1, -1));

        tableDistributionList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Uniform ID", "Name", "Quantity", "Price", "Description", "Sub Total"
            }
        ));
        tableDistributionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDistributionListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDistributionList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 129, 398, 221));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Selected Officer:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 399, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 435, -1, -1));

        txtOfficerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtOfficerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 469, 389, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Rank");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 510, -1, -1));

        txtOfficerRank.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtOfficerRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 544, 389, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 585, -1, -1));

        txtOfficerPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtOfficerPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 619, 389, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Selected Uniform:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 399, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Uniform Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 435, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Uniform Description");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Distribution Quantity:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 585, -1, -1));

        txtUniformName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUniformName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniformNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUniformName, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 469, 452, -1));

        txtUniformDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUniformDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniformDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(txtUniformDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 544, 452, -1));

        txtDistributionQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDistributionQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistributionQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtDistributionQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 619, 220, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Add to Distribution List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 686, 452, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Total  Amount RS: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 392, -1, -1));

        lblFinalTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFinalTotalPrice.setText("00000");
        getContentPane().add(lblFinalTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1208, 392, -1, -1));

        btnSaveDistributionDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveDistributionDetails.setText("Save Distribution Details");
        btnSaveDistributionDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDistributionDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveDistributionDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 469, 398, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 544, 398, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 619, 398, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Uniform Price");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 585, -1, -1));

        txtUniformPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUniformPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniformPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtUniformPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 210, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Distribution_background.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtOfficerName.setEditable(false);
        txtOfficerRank.setEditable(false);
        txtOfficerPhoneNumber.setEditable(false);

        txtUniformName.setEditable(false);
        txtUniformDescription.setEditable(false);
        txtDistributionQuantity.setEditable(true);

        DefaultTableModel model = (DefaultTableModel) tableOfficer.getModel();
        DefaultTableModel uniformModel = (DefaultTableModel) tableUniform.getModel();

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from officer");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("officer_pk"),
                    rs.getString("name"),
                    rs.getString("officer_rank"),
                    rs.getString("phoneNumber")
                });
            }
            rs = st.executeQuery("select * from uniform inner join category on uniform.category_fk = category.category_pk");
            while (rs.next()) {
                uniformModel.addRow(new Object[]{
                    rs.getString("uniform_pk"),
                    rs.getString("name"),
                    rs.getString("price"),
                    rs.getString("quantity"),
                    rs.getString("description"),
                    rs.getString("category_fk"),
                    rs.getString(8)
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown

    private void txtUniformNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniformNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniformNameActionPerformed

    private void txtDistributionQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistributionQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistributionQuantityActionPerformed

    private void txtUniformDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniformDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniformDescriptionActionPerformed

    private void btnSaveDistributionDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDistributionDetailsActionPerformed
        // TODO add your handling code here:
        if (finalTotalPrice != 0 && !txtOfficerName.getText().equals("")) {
            distributionId = getUniqueId("Detail-");

            DefaultTableModel dtm = (DefaultTableModel) tableDistributionList.getModel();
            if (tableDistributionList.getRowCount() != 0) {
                for (int i = 0; i < tableDistributionList.getRowCount(); i++) {
                    try {
                        Connection con = ConnectionProvider.getCon();
                        Statement st = con.createStatement();
                        st.executeUpdate("update uniform set quantity=quantity-" + Integer.parseInt(dtm.getValueAt(i, 2).toString()) + " where uniform_pk=" + Integer.parseInt(dtm.getValueAt(i, 0).toString()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }

            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into distributionDetail(distributionId, officer_fk, distributionDate, totalPaid) values(?,?,?,?)");
                ps.setString(1, distributionId);
                ps.setInt(2, officerPk);
                ps.setString(3, myFormat.format(cal.getTime()));
                ps.setInt(4, finalTotalPrice);
                ps.executeUpdate();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            //Creating document
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                PdfWriter.getInstance(doc, new FileOutputStream(DistributionUtils.detailPath + "" + distributionId + ".pdf"));
                doc.open();
                Paragraph projectName = new Paragraph("                                                  Military Uniforms Management System\n");
                doc.add(projectName);
                Paragraph starLine = new Paragraph(" ****************************************************************************************************************");
                doc.add(starLine);
                Paragraph details = new Paragraph("\tDistribution ID: " + distributionId + "\nDate: " + myFormat.format(cal.getTime()) + "\nTotal: " + finalTotalPrice);
                doc.add(details);
                doc.add(starLine);
                PdfPTable tb1 = new PdfPTable(5);
                PdfPCell nameCell = new PdfPCell(new Phrase("Name"));
                PdfPCell descriptionCell = new PdfPCell(new Phrase("Description"));
                PdfPCell priceCell = new PdfPCell(new Phrase("Price Per Unit"));
                PdfPCell quantityCell = new PdfPCell(new Phrase("Quantity"));
                PdfPCell subTotalPriceCell = new PdfPCell(new Phrase("Sub Total Price"));

                BaseColor backgroundColor = new BaseColor(255, 204, 51);
                nameCell.setBackgroundColor(backgroundColor);
                descriptionCell.setBackgroundColor(backgroundColor);
                priceCell.setBackgroundColor(backgroundColor);
                quantityCell.setBackgroundColor(backgroundColor);
                subTotalPriceCell.setBackgroundColor(backgroundColor);

                tb1.addCell(nameCell);
                tb1.addCell(descriptionCell);
                tb1.addCell(priceCell);
                tb1.addCell(quantityCell);
                tb1.addCell(subTotalPriceCell);
                
                for (int i=0; i<tableDistributionList.getRowCount(); i++) {
                    tb1.addCell(tableDistributionList.getValueAt(i, 1).toString());
                    tb1.addCell(tableDistributionList.getValueAt(i, 4).toString());
                    tb1.addCell(tableDistributionList.getValueAt(i, 3).toString());
                    tb1.addCell(tableDistributionList.getValueAt(i, 2).toString());
                    tb1.addCell(tableDistributionList.getValueAt(i, 5).toString());
                }
                
                doc.add(tb1);
                doc.add(starLine);
                
                OpenPdf.OpenById(distributionId);
                
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            setVisible(false);
            new ManageDistribution().setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please add some uniform to distribution list and select officer.");
        }
    }//GEN-LAST:event_btnSaveDistributionDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageDistribution().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        new ManageDistribution().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtUniformPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniformPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniformPriceActionPerformed

    private void tableOfficerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOfficerMouseClicked
        // TODO add your handling code here:
        int index = tableOfficer.getSelectedRow();
        TableModel model = tableOfficer.getModel();
        String id = model.getValueAt(index, 0).toString();
        officerPk = Integer.parseInt(id);

        String name = model.getValueAt(index, 1).toString();
        txtOfficerName.setText(name);

        String officer_rank = model.getValueAt(index, 2).toString();
        txtOfficerRank.setText(officer_rank);

        String phoneNumber = model.getValueAt(index, 3).toString();
        txtOfficerPhoneNumber.setText(phoneNumber);
    }//GEN-LAST:event_tableOfficerMouseClicked

    private void tableUniformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUniformMouseClicked
        // TODO add your handling code here:
        int index = tableUniform.getSelectedRow();
        TableModel model = tableUniform.getModel();
        String id = model.getValueAt(index, 0).toString();
        uniformPk = Integer.parseInt(id);

        String uniformName = model.getValueAt(index, 1).toString();
        txtUniformName.setText(uniformName);

        String uniformDescription = model.getValueAt(index, 4).toString();
        txtUniformDescription.setText(uniformDescription);

        String uniformPrice = model.getValueAt(index, 2).toString();
        txtUniformPrice.setText(uniformPrice);
    }//GEN-LAST:event_tableUniformMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String noOfUnits = txtDistributionQuantity.getText();
        if (!noOfUnits.equals("")) {
            String uniformName = txtUniformName.getText();
            String uniformDescription = txtUniformDescription.getText();
            String uniformPrice = txtUniformPrice.getText();

            int totalPrice = Integer.parseInt(txtDistributionQuantity.getText()) * Integer.parseInt(uniformPrice);

            int checkStock = 0;
            int checkUniformAlreadyExistInCart = 0;

            try {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM uniform WHERE uniform_pk = " + uniformPk + "");

                while (rs.next()) {
                    if (rs.getInt("quantity") >= Integer.parseInt(noOfUnits)) {
                        checkStock = 1;
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "Product is out of stock. Only " + rs.getInt("quantity") + " left.");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            if (checkStock == 1) {
                DefaultTableModel model = (DefaultTableModel) tableDistributionList.getModel();
                if (tableDistributionList.getRowCount() != 0) {
                    for (int i = 0; i < tableDistributionList.getRowCount(); i++) {
                        if (Integer.parseInt(model.getValueAt(i, 0).toString()) == uniformPk) {
                            checkUniformAlreadyExistInCart = 1;
                            JOptionPane.showMessageDialog(null, "Uniform already exist in distribution list");
                        }
                    }
                }

                if (checkUniformAlreadyExistInCart == 0) {
                    model.addRow(new Object[]{uniformPk, uniformName, noOfUnits, uniformPrice, uniformDescription, totalPrice});
                    finalTotalPrice = finalTotalPrice + totalPrice;
                    lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
                    JOptionPane.showMessageDialog(null, "Added Successfully!");
                }
                clearUniformFields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Number of Quantity is needed!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableDistributionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDistributionListMouseClicked
        // TODO add your handling code here:
        int index = tableDistributionList.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this uniform?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = tableDistributionList.getModel();
            String subTotal = model.getValueAt(index, 5).toString();
            finalTotalPrice = finalTotalPrice - Integer.parseInt(subTotal);
            lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
            ((DefaultTableModel) tableDistributionList.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_tableDistributionListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDistribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDistribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDistribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDistribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDistribution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDistributionDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFinalTotalPrice;
    private javax.swing.JTable tableDistributionList;
    private javax.swing.JTable tableOfficer;
    private javax.swing.JTable tableUniform;
    private javax.swing.JTextField txtDistributionQuantity;
    private javax.swing.JTextField txtOfficerName;
    private javax.swing.JTextField txtOfficerPhoneNumber;
    private javax.swing.JTextField txtOfficerRank;
    private javax.swing.JTextField txtUniformDescription;
    private javax.swing.JTextField txtUniformName;
    private javax.swing.JTextField txtUniformPrice;
    // End of variables declaration//GEN-END:variables
}
