/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.panel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author LENOVO LEGION
 */
public class CapPhatPanel extends javax.swing.JFrame {
    private JLabel lblHoTen;
    private JLabel lblMaSo;
    private JComboBox<String> itemDropdown;
    private JButton btnAddItem;
    private JPanel itemPanel;
    private JButton btnIssueUniform;

    /**
     * Creates new form CapPhatPanel
     */
    public CapPhatPanel(String hoTen, String maSo) {
        setTitle("Cấp Phát Quân Trang");
        setSize(1200, 800);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        // Soldier details
        lblHoTen = new JLabel("Họ Tên: " + hoTen);
        lblMaSo = new JLabel("Mã Số: " + maSo);

        // Dropdown for items
        itemDropdown = new JComboBox<>(new String[]{
                "Súng AK-47", "Đạn 7.62mm x30 viên", "Quân Phục", "Mũ cối"
        });

        // "Add +" button to add more items
        btnAddItem = new JButton("Thêm +");
        btnAddItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addItemToPanel();
            }
        });

        // Panel for dynamically added items
        itemPanel = new JPanel();
        itemPanel.setLayout(new BoxLayout(itemPanel, BoxLayout.Y_AXIS));

        // Issue uniform button
        btnIssueUniform = new JButton("Cấp Phát Quân Trang");
        btnIssueUniform.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                issueUniform(hoTen);
            }
        });

        // Layout setup
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.add(lblHoTen);
        formPanel.add(lblMaSo);
        formPanel.add(new JLabel("Chọn Quân Trang:"));
        formPanel.add(itemDropdown);

        JPanel mainPanel = new JPanel(new BorderLayout());
        mainPanel.add(formPanel, BorderLayout.NORTH);
        mainPanel.add(btnAddItem, BorderLayout.CENTER);
        mainPanel.add(new JScrollPane(itemPanel), BorderLayout.SOUTH);
        mainPanel.add(btnIssueUniform, BorderLayout.PAGE_END);

        add(mainPanel);
        setVisible(true);
    }

    // Method to add a new row with a JComboBox to select items
    private void addItemToPanel() {
    // Create a new row panel with left alignment
    JPanel itemRow = new JPanel(new FlowLayout(FlowLayout.LEFT));

    // Add a label for the dropdown
    JLabel label = new JLabel("Chọn Quân Trang: ");
    itemRow.add(label);

    // Create a new item dropdown
    JComboBox<String> newItemDropdown = new JComboBox<>(new String[]{
            "Súng AK-47", "Đạn 7.62mm x30 viên", "Quân Phục", "Mũ cối"
    });

    // Add the dropdown to the row
    itemRow.add(newItemDropdown);

    // Add the row to the panel
    itemPanel.add(itemRow);
    
    // Revalidate and repaint the panel to show the new row
    itemPanel.revalidate();
    itemPanel.repaint();
}

    // Method to handle uniform issuance
    private void issueUniform(String hoTen) {
        JOptionPane.showMessageDialog(this, "Đã cấp phát quân trang thành công cho " + hoTen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapPhatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapPhatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapPhatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapPhatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
            new CapPhatPanel("Nguyễn Văn A", "12345").setVisible(true); // Example data
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
