/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.panel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import com.toedter.calendar.JCalendar;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * @author LENOVO LEGION
 */
public class QuanNhanPanel extends javax.swing.JFrame {
    private JTextField txtHoTen;
    private JTextField txtMaSo;
    private JTextField txtDonVi;
    private JTextField txtCapBac;
    private JButton btnAdd;
    private JButton btnUpdate;
    private JButton btnDelete;
    private JComboBox<String> rankDropdown;
    private JCalendar calendar;
    private JTable table;
    private JTextField txtNgaySinh;

    /**
     * Creates new form QuanNhanPanel
     */
     public QuanNhanPanel() {
        setTitle("Quản Lý Quân Nhân");
        setSize(1200, 800);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        // Khởi tạo các thành phần
        txtHoTen = new JTextField(20);
        txtMaSo = new JTextField(20);
        txtDonVi = new JTextField(20);
                
        // Khởi tạo JCalendar và định dạng ngày sinh
        calendar = new JCalendar();
        calendar.setPreferredSize(new Dimension(300, 200)); // Điều chỉnh kích thước lịch
        calendar.setWeekOfYearVisible(false); // Ẩn số tuần nếu không cần
        txtNgaySinh = new JTextField(20);
        txtNgaySinh.setEditable(false); // Chỉ đọc

        // Lắng nghe sự kiện thay đổi ngày để hiển thị theo định dạng dd/MM/yyyy
        calendar.addPropertyChangeListener("calendar", evt -> {
            Date selectedDate = calendar.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = dateFormat.format(selectedDate);
            txtNgaySinh.setText(formattedDate);
        });
        
        
        rankDropdown = new JComboBox<>(new String[] {
                "Binh Nhì", "Binh Nhất", "Hạ Sĩ", "Trung Sĩ", "Thượng Sĩ", "Thiếu Úy", "Trung Úy", "Đại Úy"
        });

        // Khởi tạo bảng
        table = new JTable(new DefaultTableModel(new Object[] {
                "Họ Tên", "Mã Số", "Đơn Vị", "Cấp Bậc", "Ngày Sinh"
        }, 0));
        JScrollPane tableScrollPane = new JScrollPane(table);
        tableScrollPane.setPreferredSize(new Dimension(800, 200)); // Điều chỉnh kích thước bảng

        // Khởi tạo các nút
        btnAdd = new JButton("Thêm");
        btnUpdate = new JButton("Sửa");
        btnDelete = new JButton("Xóa");

        // Bố trí các thành phần bằng GridBagLayout
        JPanel formPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0;
        gbc.gridy = 0;
        formPanel.add(new JLabel("Họ Tên:"), gbc);
        gbc.gridx = 1;
        formPanel.add(txtHoTen, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        formPanel.add(new JLabel("Mã Số:"), gbc);
        gbc.gridx = 1;
        formPanel.add(txtMaSo, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        formPanel.add(new JLabel("Đơn Vị:"), gbc);
        gbc.gridx = 1;
        formPanel.add(txtDonVi, gbc);

        gbc.gridx = 0;
        gbc.gridy = 4;
        formPanel.add(new JLabel("Cấp Bậc:"), gbc);
        gbc.gridx = 1;
        formPanel.add(rankDropdown, gbc);

        gbc.gridx = 0;
        gbc.gridy = 3;
        formPanel.add(new JLabel("Ngày Sinh:"), gbc);
        gbc.gridx = 1;
        formPanel.add(calendar, gbc);

        gbc.gridx = 2;
        gbc.gridy = 3;
        formPanel.add(txtNgaySinh, gbc);

        // Panel chứa các nút
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnAdd);
        buttonPanel.add(btnUpdate);
        buttonPanel.add(btnDelete);

        // Panel chính để chứa tất cả thành phần
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.add(formPanel, BorderLayout.NORTH);
        mainPanel.add(tableScrollPane, BorderLayout.CENTER);
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        add(mainPanel);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanNhanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanNhanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanNhanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanNhanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanNhanPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
